"""Evidence-led discretionary fundamental strategy with explicit human approval."""

from aquant.strategies.discretionary.beliefs import BayesianBeliefEngine, BeliefUpdate
from aquant.strategies.discretionary.calibration import (
    CalibrationLedger,
    CalibrationOutcome,
    CalibrationSummary,
)
from aquant.strategies.discretionary.models import (
    AcquisitionBasis,
    BeliefSnapshot,
    CausalNode,
    CausalStage,
    CompetingHypothesis,
    EstimateVintage,
    EvidenceAssessment,
    EvidenceFamily,
    EvidenceMaturity,
    EvidenceObservation,
    EvidenceQuality,
    HypothesisKind,
    HypothesisLikelihood,
    HypothesisProbability,
    KeyVariable,
    LeadingIndicator,
    OutcomeLayer,
    RadarSignal,
    ResearchCase,
    ResearchStage,
    ValidationDomain,
)
from aquant.strategies.discretionary.positioning import (
    AllocationAction,
    AllocationApproval,
    AllocationProposal,
    AllocationTier,
    MarketExpectationSnapshot,
    PayoffProfile,
    PositionPolicy,
    PositionSizingEngine,
    PriorPositionState,
    approve_allocation,
    build_approved_target_portfolio,
)
from aquant.strategies.discretionary.strategy import (
    DiscretionaryDecision,
    DiscretionaryFundamentalStrategy,
)

__all__ = [
    "AcquisitionBasis",
    "AllocationAction",
    "AllocationApproval",
    "AllocationProposal",
    "AllocationTier",
    "BayesianBeliefEngine",
    "BeliefSnapshot",
    "BeliefUpdate",
    "CalibrationLedger",
    "CalibrationOutcome",
    "CalibrationSummary",
    "CausalNode",
    "CausalStage",
    "CompetingHypothesis",
    "DiscretionaryDecision",
    "DiscretionaryFundamentalStrategy",
    "EstimateVintage",
    "EvidenceAssessment",
    "EvidenceFamily",
    "EvidenceMaturity",
    "EvidenceObservation",
    "EvidenceQuality",
    "HypothesisKind",
    "HypothesisLikelihood",
    "HypothesisProbability",
    "KeyVariable",
    "LeadingIndicator",
    "MarketExpectationSnapshot",
    "OutcomeLayer",
    "PayoffProfile",
    "PositionPolicy",
    "PositionSizingEngine",
    "PriorPositionState",
    "RadarSignal",
    "ResearchCase",
    "ResearchStage",
    "ValidationDomain",
    "approve_allocation",
    "build_approved_target_portfolio",
]
